name: Daily Backup
on:
  schedule:
    - cron: "0 2 * * *" # Runs daily at 2 AM UTC
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Backup Script
        run: bash bash-scripts/backup.sh
